config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'
  resources :users
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root                'static_pages#home'

  resources :users
  resources :votes,           only: [:create, :destroy]
  resources :topics,      only: [:index, :new, :create, :destroy, :show]
  resources :trends, only: [:index, :new, :create, :destroy, :show] do
     resources :submissions,   only: [:new, :create, :destroy]
     resources :topics, only: [:new, :create, :destroy]

  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :editor, class_name: "User"

  has_many :submissions
  has_many :users, through: :submissions
  belongs_to :trend, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  validates :summary, presence: true, length: { maximum: 499 }
  validates :trending_reason, presence: true, length: { maximum: 499 }
  validates :title,  :presence => true, :length => { maximum: 50 },
            :uniqueness => { case_sensitive: false }




end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def new
    @topic = Topic.new
  end

  def index
    @topics = Topic.all
  end


  def create
    @new_topic = Topic.new(topic_params)
    @new_topic.trend_id = params[:trend_id]
    @new_topic.user_id = current_user.id 
   # @current_trend = Trend.find(@new_topic.trend_id)
    if @new_topic.save
      flash[:success] = "New Topic Created"
      redirect_to root_path
    else
      render 'new'
    end
  end


  def show
    @topic = Topic.find(params[:id])
    @submission = current_user.submissions.build if logged_in?
    @link = Link.new
    @user = current_user
    @submissions = @topic.submissions.paginate(page: params[:page])
  end


  private

  def topic_params
    params.require(:topic).permit(:title, :summary, :trending_reason, :imageURL)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_new_topic_form.html.erb
<% if !params[:topic].nil? %>
<%= render 'shared/error_messages', object: @topic %>
<% end %>
<div class = "submission-form">
	<%= form_for(Topic.new, url: trend_topics_path(params[:id])) do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>

		<%= f.label :summary %>
		<div class="field">
  			<%= f.text_area :summary %>
		</div>

		<%= f.label :trending_reason %>
		<div class="field">
  			<%= f.text_area :trending_reason %>
		</div>
		
		<% if false %>
		<%= f.label :Image_URL%>(Optional)
		<%= f.text_field :imageURL, class: 'form-control' %>
		<% end %>
		<%= f.submit "Submit", class: "btn btn-primary" %>
	<% end %>



</div>

app/views/topics/_topic.html.erb
<section class="post_info" id="topic-<%= topic.id %>">
    <h1>
      <%= topic.title %>
      <br>
    </h1>

    <h2>

     <%= topic.summary%>
      <br>
      <br>

      <%=topic.trending_reason %>
      <br>
      <br>

    </h2>

  </section>

app/views/topics/index.html.erb
haha

app/views/topics/new.html.erb
  <aside class="col-md-16">
  <section class="post_form content-float">
    <%= render 'new_topic_form' %>
  </section>
</aside>

app/views/topics/show.html.erb
<% provide(:title, @topic.title) %>
<div class="col-md-15">
  <section class="user_info content-float">
    <h1>
      <%= @topic.title %>
      <br>
    </h1>

    <h2>
      <%= @topic.summary %>
      <br>
      <br>

      <%= @topic.trending_reason %>
      <br>
      <br>

      <% if @topic.imageURL?%>
      <img src="<%=@topic.imageURL%>">
      <br>
      <br>
      <%end%>

    </h2>

  </section>
</div>

<% if logged_in? %>
<aside>
<%= render "shared/submission_form" %>
</aside>
<% end %>

<% if @submissions.any? %>
<section class="submissions">
  <%= render @submissions %>
</section>
<%= will_paginate @submissions %>
<% end %>