config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'
  resources :users
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root                'static_pages#home'

  resources :users
  resources :votes,           only: [:create, :destroy]
  resources :topics,      only: [:index, :new, :create, :destroy, :show]
  resources :trends, only: [:index, :new, :create, :destroy, :show] do
     resources :submissions,   only: [:new, :create, :destroy]
     resources :topics, only: [:new, :create, :destroy]

  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<div>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
</div>
<% end %>

app/views/shared/_submission_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for(Submission.new, url: trend_submissions_path(params[:id])) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>


      <%= f.text_field :title, :placeholder => "Title", class: "form-control" %>

      
      <%= f.text_area :content, :placeholder => "Write Your Post", :rows => 15, class: "form-control" %>

      <%= f.fields_for(Link.new) do |builder| %>
 
        <%= builder.text_field :url, :placeholder => "Link", class: "form-control" %>
      <% end %>

      <%= f.submit "Submit", class: "btn btn-primary" %>

    <% end %>
    </div>
  </div>

</div>

app/views/shared/_user_info.html.erb
<div class = "profile_partial_title"> <%= link_to gravatar_for(@user,50), @user %><%=@user.username%></div>
<br>
<br>
<h4 class = "profile_partial_info">Rank: </h4>
<h4 class = "profile_partial_info">Points: <%= @user.reputation%> </h4>
<h4 class = "profile_partial_info">Posts: <%=@user.submissions.count%> </h4>

app/views/shared/_votes.html.erb
<% voteClasses = voteButtonClasses(votable) %>

  <%= link_to "&#9650;".html_safe, votes_path( { upvote: true,
                                       votable_id: votable.id }),
                                       method: :post,
                                       remote: true,
                                       class: voteClasses[0]
                                        %>

<br>
<%=votable.total_upvotes%>
<br>
<%= link_to "&#9660;".html_safe, votes_path( { upvote: false,
                                       votable_id: votable.id }),
                                       method: :post,
                                       remote: true,
                                       class: voteClasses[1]
                                       %>