config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'
  resources :users
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root                'static_pages#home'

  resources :users
  resources :votes,           only: [:create, :destroy]
  resources :topics,      only: [:index, :new, :create, :destroy, :show]
  resources :trends, only: [:index, :new, :create, :destroy, :show] do
     resources :submissions,   only: [:new, :create, :destroy]
     resources :topics, only: [:new, :create, :destroy]

  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path%></li>
          <% if logged_in? %>
          <li> <%=link_to "All Trends", trends_path %> </li>
          <li><%= link_to "Profile", current_user %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Settings <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", @current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", logout_path, method: :delete %>
              </li>
            </ul>


          </li>

          <% else %>
          <li><%= link_to "Login", sessions_new_path %></li>


          <% end %>

         </ul>

         <ul class="nav navbar-nav navbar-left">
            <% if logged_in? %>
              <li><a href="#menu-toggle" class="trending-button" id="menu-toggle">Trending</a></li>
              <li>
                  <%= form_tag(trends_path, :method => "get", id: "search-form") do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Search Trends", class: "search_bar" %>
                  <% end %>


        </li>


            <%end%>

          </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_sidebar.html.erb
 <div id="wrapper">
    <div id="sidebar-wrapper">

      <ul class="sidebar-nav">

        <li class="sidebar-brand">
          <a href="#" id="Trending-Banner">   </a>
        </li>
        <%-#load_trends is in static pages helper %>
        <% Trend.last(10).each do |trend| %>
           <li><%= link_to trend.title, trend %></li>
        <% end %>

      </ul>
  </div>

</div>

    <script src="assets/javascripts/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script>

    $("#menu-toggle").click(function(e) 
    {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<head>
  <title>Metahash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<html>

<body>
<%= render "layouts/header" %>

<body>

  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>


</body>
</body>
</html>